version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    target_branch: 'master'

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - 'digitals'
    default_labels:
      - 'dependencies'
