name: check

on: pull_request

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install packages
        run: npm install
      - name: Linter
        run: npm run lint
      - name: Run tests
        run: npm run test
